[package]
name = "pigeon-spool"
description = "Durable message spool, queue leases and retry scheduling."
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true
publish.workspace      = true

[dependencies]
pigeon-types = { workspace = true }
