[package]
name = "pigeon-db"
description = "SQLite storage, migrations and repositories."
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true

[dependencies]
pigeon-types = { workspace = true }
