[package]
name = "pigeon-dns"
description = "DNS resolution and MX/SPF/DKIM/DMARC/PTR validation."
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true

[dependencies]
pigeon-types = { workspace = true }
