[package]
name = "pigeon-auth"
description = "DKIM signing/verification, ARC sealing, SRS, DMARC evaluation."
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true
publish.workspace      = true

[dependencies]
pigeon-types = { workspace = true }
rsa = { workspace = true }
mail-auth = { workspace = true }
mail-parser = { workspace = true }
hmac = { workspace = true }
sha2 = { workspace = true }
subtle = { workspace = true }
zeroize = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread"] }
