[package]
name = "pigeon-smtp"
description = "SMTP protocol: receiver state machine and delivery client."
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true

[dependencies]
pigeon-types = { workspace = true }
