[package]
name = "pigeon-smtp"
description = "SMTP protocol: receiver state machine and delivery client."
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true
publish.workspace      = true

[dependencies]
pigeon-types = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "io-util", "net", "time", "test-util"] }
pigeon-testkit = { workspace = true }
