[package]
name = "pigeon-cli"
description = "Pigeon command line interface."
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true
publish.workspace      = true

[dependencies]
clap = { workspace = true }
pigeon-types = { workspace = true }
pigeon-route = { workspace = true }
rusqlite = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }
pigeon-config = { workspace = true }
pigeon-db = { workspace = true }
pigeon-auth = { workspace = true }
pigeon-dns = { workspace = true }

[[bin]]
name = "pigeon"
path = "src/main.rs"
